### ISSUE TITLE
Supporting a `scope` config.

### ISSUE THREAD

**Issue by jamen** [Devcord/cordlr-loader#2]
It would be really nice if you could scope how commands are run.  For example, restrict it to certain guilds, channels, or even users (for things like self-bots).

I can't think of a good config for this, any ideas?

**Comment by mees-** [comment]
I also think we should allow plugins to listen to all messages, for example to echo them to other destinations, also maybe we could create a loader with an express like architecture with middleware, so we could have a middleware handling permissions etc
